/**
 * jobs/autoScenarios.js
 * Automatically generate and post scenarios using agent + persona
 */

import { logger } from "../util/logger.js";
import { incCounter } from "../util/metrics.js";
import { generate as llmGenerate } from "../services/ai/llm.js";
import { getCollection } from "../db/mongo.js";
import webhooks from "../services/webhooks.js";
import personas from "../services/persona.js";

/**
 * Generate a new scenario using LLM
 * @param {object} context - Guild context
 * @returns {Promise<object>} - Scenario object {prompt, correctAnswer, hostPersonaName, tags}
 */
async function generateScenario(context = {}) {
  const systemPrompt = `You are a creative scenario generator for the Elio/Communiverse universe.
Generate trivia questions or roleplay prompts that are fun, engaging, and lore-accurate.
Focus on characters, locations, relationships, and plot points from the Elio (2025) film.`;

  const userPrompt = `Create a new trivia question or scenario prompt about the Elio universe.
Format your response as JSON:
{
  "prompt": "The question or scenario setup",
  "correctAnswer": "The correct answer (if trivia)",
  "hostPersonaName": "Elio" or "Olga" or "Glordon",
  "tags": ["tag1", "tag2"]
}`;

  try {
    const result = await llmGenerate({
      prompt: userPrompt,
      system: systemPrompt,
      maxTokens: 300,
      temperature: 0.9,
    });

    if (!result.ok) {
      throw new Error(`LLM generation failed: ${result.error.message}`);
    }

    // Parse JSON from response
    const text = result.data.text.trim();
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON found in LLM response");
    }

    const scenario = JSON.parse(jsonMatch[0]);
    return scenario;
  } catch (error) {
    logger.error("[JOB:AutoScenarios] Generation error:", error);
    return null;
  }
}

/**
 * Auto-scenario job: generate and occasionally post scenarios
 */
export async function run(client) {
  try {
    logger.info("[JOB:AutoScenarios] Running auto-scenario generation...");

    // 30% chance to actually post
    if (Math.random() > 0.3) {
      logger.info("[JOB:AutoScenarios] Skipping this run (probability)");
      return;
    }

    // Generate scenario
    const scenario = await generateScenario();
    if (!scenario) {
      logger.warn("[JOB:AutoScenarios] Failed to generate scenario");
      return;
    }

    // Save to database
    const scenariosCol = getCollection("scenarios");
    const inserted = await scenariosCol.insertOne({
      ...scenario,
      enabled: true,
      weight: 1.0,
      createdAt: new Date(),
      autoGenerated: true,
    });

    logger.info(`[JOB:AutoScenarios] Created scenario: ${scenario.prompt.substring(0, 60)}...`);

    // Randomly post to a guild (pick first guild for now)
    const guilds = client.guilds.cache;
    if (guilds.size === 0) {
      logger.warn("[JOB:AutoScenarios] No guilds available");
      return;
    }

    const guild = guilds.first();
    const channelsCol = getCollection("schedules");
    const schedule = await channelsCol.findOne({
      guildId: guild.id,
      kind: "scenario",
      enabled: true,
    });

    if (!schedule || !schedule.channelId) {
      logger.info("[JOB:AutoScenarios] No scenario channel configured");
      return;
    }

    const channel = await client.channels.fetch(schedule.channelId);
    if (!channel) {
      logger.warn(`[JOB:AutoScenarios] Channel ${schedule.channelId} not found`);
      return;
    }

    // Get host persona
    const hostPersona = await personas.getByName(scenario.hostPersonaName || "Elio");
    if (!hostPersona) {
      logger.warn(`[JOB:AutoScenarios] Host persona not found: ${scenario.hostPersonaName}`);
      return;
    }

    // Post as persona
    const message = `🌌 **New Scenario!**\n\n${scenario.prompt}`;
    await webhooks.personaSay(channel.id, hostPersona, { content: message });

    incCounter("auto_scenarios_posted_total", { guild: guild.id });
    logger.info(`[JOB:AutoScenarios] ✅ Posted scenario to ${channel.name}`);
  } catch (error) {
    logger.error("[JOB:AutoScenarios] Error:", error);
    incCounter("auto_scenarios_errors_total");
  }
}

export default { run };
